name: Artifacts

on:
  push:
    branches:
      - main
      - increment_2
  pull_request:
    branches: [ main ]

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build server
        run: |
          cd cmd/server
          mkdir release
          GOOS=windows GOARCH=amd64 go build -o bin/app-amd64-windows.exe -ldflags "-X main.BuildVersion=v1.0.1 -X main.BuildCommit=${{ github.sha }} -X 'main.BuildDate=$(date +'%Y/%m/%d %H:%M:%S')'" main.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: copy artifacts
          path: |
            cmd/server/bin
            cmd/client/bin
